import Head from 'next/head'
import {MuiThemeProvider} from '@material-ui/core/styles'
import React, {ChangeEvent, Fragment, useEffect, useState} from "react";
import { ThemeProvider} from '@mui/material/styles';
import {Avatar, Box, Button, Container, CssBaseline, Grid, TextField, Typography} from "@mui/material";
import {makeStyles, createStyles} from '@material-ui/styles'
import PaymentIcon from '@mui/icons-material/Payment';
import {LocalizationProvider} from '@mui/x-date-pickers';
import {AdapterDateFns} from '@mui/x-date-pickers/AdapterDateFns';
import {DatePicker} from "@mui/x-date-pickers";
// import {MuiThemeProvider, createMuiTheme } from '@material-ui/core/styles'

// import {createMuiTheme} from "@material-ui/core";
import clsx from "clsx";
import {CurrentRateAPI} from "../api/api";
// import makeStyles from '@material-ui/styles'
// export {default} from './Buttons'


// import {makeStyles, createStyles} from '@mui/styles'
// import {makeStyles, createStyles} from '@material-ui/core'
import Image from 'next/image'
// import styles from '../styles/main.css'

import {createTheme} from "@material-ui/core";

// const theme2 = createMuiTheme({
// })
// const themev0 = getMuiTheme({})

const theme = createTheme({

});
const useStyles = makeStyles({
    btn: {
        border: 'none',
        margin: 20,
        width: 400,
        height: 45,
        borderRadius: 6,
        textTransform: 'uppercase',
        boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .3)',
        cursor: 'pointer',
        color: '#fff',
        backgroundSize: '200%',
        transition: '1s',
        backgroundPosition: 'right',
        '&:hover': {
            backgroundPosition: 'left'
        }
    },
    btn1: {
        backgroundImage: 'linear-gradient(45deg, #FFC312, #EE5A24, #00A8FF)'
    },
    container: {
        position: 'absolute',
        left: '50%',
        // top: '50%',
        transform: 'translate(-50%, -15%)',
        textAlign: 'center'
    },

})


export default function Home() {
        const classes = useStyles()
        // const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
        //     event.preventDefault();
        //     const data = new FormData(event.currentTarget);
        //     // console.log({
        //     //     email: data.get('email'),
        //     //     password: data.get('password'),
        //     // });
        // };
        //
        //
        // const handleCardNumber = () => {
        //     // @ts-ignore
        //     const rawText = [...card.split(' ').join('')]
        //     const creditCard = [] as string[]
        //     rawText.forEach((t, i) => {
        //         if (i % 4 === 0) creditCard.push(' ')
        //         creditCard.push(t)
        //     })
        //     return creditCard.join('')
        // }
        // const handleChangeCardNumber = (e: any) => {
        //     const re = /[0-9]+/g;
        //     if (e.target.value === '' || re.test(e.target.value)) {
        //         setCard(e.target.value)
        //     } else (setCard(""))
        // }
        // const handleChangeDate = (e: any, keyboardInputValue: string | undefined) => {
        //     // @ts-ignore
        //     setDateKey(keyboardInputValue)
        //     setDateCard(e)
        // }
        // const handleChangeAmount = (e: any) => {
        //     const re = /[0-9]+/g;
        //     if (e.target.value === '' || re.test(e.target.value)) {
        //         setAmount(e.target.value)
        //     } else (setAmount(""))
        // }
        // const handleChangeCvv = (e: any) => {
        //     const re = /[0-9]+/g;
        //     if (e.target.value === '' || re.test(e.target.value)) {
        //         setCvv(e.target.value)
        //      } else (setCvv(""))
        // }
        //
        //

        // @ts-ignore
        return (
            <React.Fragment>
            // <ThemeProvider theme={theme}>
            //     <CssBaseline/>
            <div className={classes.container}>
                <Button
                    // disabled={card.length !== 20 ||
                    // cvv.length !== 3 || amount.length < 1 || dateKey.length !== 7}
                    className={ `${classes.btn} ${classes.btn1}` }
                    // type="submit"
                    // fullWidth
                    // variant="contained"
                    // onClick={sendPay}
                    // sx={{mt: 3, mb: 2,} }
                >
                    Pay
                </Button>
            </div>
            // </ThemeProvider>
</React.Fragment>
        )
    }
// const [card, setCard] = useState('')
// const [dateCard, setDateCard] = useState('')
// const [amount, setAmount] = useState('');
// const [cvv, setCvv] = useState('');



//     return (
//
//
//
//
//         <div >
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//         </div>
//     )
// }
